// BuchoCheioVuejs/src/App.tsx
import { useState } from "react";
import { LandingPage } from "./components/LandingPage";
import { UserNavigation } from "./components/UserNavigation";
import { RestaurantNavigation } from "./components/RestaurantNavigation";
import { Toaster } from "./components/ui/sonner";

type UserType = 'seeker' | 'restaurant' | null;

export default function App() {
  const [userType, setUserType] = useState<UserType>(null);

  const handleUserTypeSelect = (type: UserType) => {
    setUserType(type);
  };

  const handleBack = () => {
    setUserType(null);
  };

  return (
    <>
      {userType === null && (
        <LandingPage onUserTypeSelect={handleUserTypeSelect} />
      )}
      
      {userType === 'seeker' && (
        <UserNavigation onBack={handleBack} />
      )}
      
      {userType === 'restaurant' && (
        <RestaurantNavigation onBack={handleBack} />
      )}
      
      <Toaster />
    </>
  );
}

// BuchoCheioVuejs/src/App.vue
<template>
  <div>
    <LandingPage v-if="userType === null" @user-type-select="handleUserTypeSelect" />
    <UserNavigation v-else-if="userType === 'seeker'" @back="handleBack" />
    <RestaurantNavigation v-else-if="userType === 'restaurant'" @back="handleBack" />
    <Toaster />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import LandingPage from './components/LandingPage.vue'
import UserNavigation from './components/UserNavigation.vue'
import RestaurantNavigation from './components/RestaurantNavigation.vue'
import { Toaster } from './components/ui/sonner'

type UserType = 'seeker' | 'restaurant' | null

const userType = ref<UserType>(null)

const handleUserTypeSelect = (type: UserType) => {
  userType.value = type
}

const handleBack = () => {
  userType.value = null
}
</script>
