// BuchoCheioVuejs/src/components/MealFinder.tsx
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Badge } from "./ui/badge";
import { Separator } from "./ui/separator";
import { Search, MapPin, Clock, Phone, Utensils, Star } from "lucide-react";

interface Restaurant {
  id: string;
  name: string;
  address: string;
  phone: string;
  cuisine: string;
  distance: string;
  rating: number;
  isOpen: boolean;
  meals: Array<{
    id: string;
    name: string;
    description: string;
    category: string;
    quantity: number;
    availableUntil: string;
  }>;
}

const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Café Sunny",
    address: "Rua Principal 123, Centro",
    phone: "(11) 99123-4567",
    cuisine: "Brasileira",
    distance: "0,8 km",
    rating: 4.5,
    isOpen: true,
    meals: [
      {
        id: "1",
        name: "Sopa de Legumes",
        description: "Sopa fresca de legumes com pão",
        category: "sopa",
        quantity: 20,
        availableUntil: "18:00"
      },
      {
        id: "2",
        name: "Sanduíche de Frango",
        description: "Sanduíche de frango grelhado com salada",
        category: "sanduiche",
        quantity: 15,
        availableUntil: "16:00"
      }
    ]
  },
  {
    id: "2",
    name: "Cozinha do Mario",
    address: "Av. das Flores 456, Bela Vista",
    phone: "(11) 99234-5678",
    cuisine: "Italiana",
    distance: "1,9 km",
    rating: 4.8,
    isOpen: true,
    meals: [
      {
        id: "3",
        name: "Macarrão ao Molho",
        description: "Macarrão clássico com molho marinara",
        category: "principal",
        quantity: 12,
        availableUntil: "19:00"
      },
      {
        id: "4",
        name: "Salada Caesar",
        description: "Alface fresca com parmesão e croutons",
        category: "salada",
        quantity: 8,
        availableUntil: "17:30"
      }
    ]
  },
  {
    id: "3",
    name: "Taco Express",
    address: "Rua dos Pinheiros 789, Vila Madalena",
    phone: "(11) 99345-6789",
    cuisine: "Mexicana",
    distance: "3,4 km",
    rating: 4.3,
    isOpen: false,
    meals: []
  }
];

export function MealFinder() {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCuisine, setSelectedCuisine] = useState("all");
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [restaurants] = useState<Restaurant[]>(mockRestaurants);

  const filteredRestaurants = restaurants.filter((restaurant) => {
    const matchesSearch = searchQuery === "" || 
      restaurant.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      restaurant.address.toLowerCase().includes(searchQuery.toLowerCase()) ||
      restaurant.meals.some(meal => 
        meal.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        meal.description.toLowerCase().includes(searchQuery.toLowerCase())
      );
    
    const matchesCuisine = selectedCuisine === "all" || restaurant.cuisine === selectedCuisine;
    
    const matchesCategory = selectedCategory === "all" || 
      restaurant.meals.some(meal => meal.category === selectedCategory);

    return matchesSearch && matchesCuisine && matchesCategory;
  });

  const getCategoryColor = (category: string) => {
    const colors: { [key: string]: string } = {
      sopa: "bg-blue-100 text-blue-800",
      sanduiche: "bg-green-100 text-green-800",
      salada: "bg-yellow-100 text-yellow-800",
      principal: "bg-red-100 text-red-800",
      sobremesa: "bg-purple-100 text-purple-800",
      outro: "bg-gray-100 text-gray-800"
    };
    return colors[category] || colors.outro;
  };

  const totalMealsAvailable = filteredRestaurants.reduce(
    (total, restaurant) => total + restaurant.meals.reduce((sum, meal) => sum + meal.quantity, 0),
    0
  );

  return (
    <div className="mt-6 space-y-6">
      {/* Search and Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Search className="w-5 h-5" />
            Encontrar Refeições Disponíveis
          </CardTitle>
          <CardDescription>
            Busque por restaurantes e refeições disponíveis na sua região.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="search">Buscar</Label>
              <Input
                id="search"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Busque restaurantes, refeições ou localizações..."
              />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="cuisine">Tipo de Culinária</Label>
                <Select value={selectedCuisine} onValueChange={setSelectedCuisine}>
                  <SelectTrigger>
                    <SelectValue placeholder="Todas as culinárias" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Todas as culinárias</SelectItem>
                    <SelectItem value="Brasileira">Brasileira</SelectItem>
                    <SelectItem value="Italiana">Italiana</SelectItem>
                    <SelectItem value="Mexicana">Mexicana</SelectItem>
                    <SelectItem value="Asiática">Asiática</SelectItem>
                    <SelectItem value="Mediterrânea">Mediterrânea</SelectItem>
                    <SelectItem value="Indiana">Indiana</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="category">Categoria da Refeição</Label>
                <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                  <SelectTrigger>
                    <SelectValue placeholder="Todas as categorias" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Todas as categorias</SelectItem>
                    <SelectItem value="sopa">Sopa</SelectItem>
                    <SelectItem value="sanduiche">Sanduíche</SelectItem>
                    <SelectItem value="salada">Salada</SelectItem>
                    <SelectItem value="principal">Prato Principal</SelectItem>
                    <SelectItem value="sobremesa">Sobremesa</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Summary */}
            <div className="bg-muted rounded-lg p-4">
              <div className="flex items-center justify-between">
                <span>{filteredRestaurants.length} restaurantes encontrados</span>
                <span>{totalMealsAvailable} refeições disponíveis</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Results */}
      <div className="space-y-4">
        {filteredRestaurants.length === 0 ? (
          <Card>
            <CardContent className="text-center py-8">
              <p className="text-muted-foreground">
                Nenhum restaurante ou refeição encontrada com os critérios de busca.
              </p>
            </CardContent>
          </Card>
        ) : (
          filteredRestaurants.map((restaurant) => (
            <Card key={restaurant.id} className={!restaurant.isOpen ? "opacity-60" : ""}>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      {restaurant.name}
                      {!restaurant.isOpen && (
                        <Badge variant="destructive">Fechado</Badge>
                      )}
                    </CardTitle>
                    <CardDescription className="flex items-center gap-4 mt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-4 h-4" />
                        {restaurant.address} • {restaurant.distance}
                      </span>
                      <span className="flex items-center gap-1">
                        <Phone className="w-4 h-4" />
                        {restaurant.phone}
                      </span>
                    </CardDescription>
                  </div>
                  <div className="text-right">
                    <div className="flex items-center gap-1 mb-1">
                      <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                      <span>{restaurant.rating}</span>
                    </div>
                    <Badge variant="secondary">{restaurant.cuisine}</Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {restaurant.meals.length === 0 ? (
                  <p className="text-muted-foreground">Nenhuma refeição disponível no momento</p>
                ) : (
                  <>
                    <div className="flex items-center gap-2 mb-4">
                      <Utensils className="w-4 h-4" />
                      <span>{restaurant.meals.length} tipos de refeição • {restaurant.meals.reduce((sum, meal) => sum + meal.quantity, 0)} porções disponíveis</span>
                    </div>
                    <div className="space-y-3">
                      {restaurant.meals.map((meal) => (
                        <div key={meal.id} className="flex items-center justify-between p-3 bg-muted rounded-lg">
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                              <h4>{meal.name}</h4>
                              <Badge className={getCategoryColor(meal.category)}>
                                {meal.category}
                              </Badge>
                            </div>
                            {meal.description && (
                              <p className="text-muted-foreground text-sm mb-2">{meal.description}</p>
                            )}
                            <div className="flex items-center gap-4 text-sm text-muted-foreground">
                              <span>{meal.quantity} porções</span>
                              <span className="flex items-center gap-1">
                                <Clock className="w-3 h-3" />
                                Até {meal.availableUntil}
                              </span>
                            </div>
                          </div>
                          <Button 
                            disabled={!restaurant.isOpen}
                            className="ml-4"
                          >
                            Reservar
                          </Button>
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}

// BuchoCheioVuejs/src/components/MealFinder.vue
<template>
  <div class="mt-6 space-y-6">
    <!-- Search and Filters -->
    <Card>
      <CardHeader>
        <CardTitle class="flex items-center gap-2">
          <Search class="w-5 h-5" />
          Find Available Meals
        </CardTitle>
        <CardDescription>
          Search for restaurants and available meals in your area.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div class="space-y-4">
          <div class="space-y-2">
            <Label for="search">Search</Label>
            <Input
              id="search"
              v-model="searchQuery"
              placeholder="Search restaurants, meals, or locations..."
            />
          </div>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="cuisine">Cuisine Type</Label>
              <Select v-model="selectedCuisine">
                <SelectTrigger>
                  <SelectValue placeholder="All cuisines" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All cuisines</SelectItem>
                  <SelectItem value="American">American</SelectItem>
                  <SelectItem value="Italian">Italian</SelectItem>
                  <SelectItem value="Mexican">Mexican</SelectItem>
                  <SelectItem value="Asian">Asian</SelectItem>
                  <SelectItem value="Mediterranean">Mediterranean</SelectItem>
                  <SelectItem value="Indian">Indian</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div class="space-y-2">
              <Label for="category">Meal Category</Label>
              <Select v-model="selectedCategory">
                <SelectTrigger>
                  <SelectValue placeholder="All categories" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All categories</SelectItem>
                  <SelectItem value="soup">Soup</SelectItem>
                  <SelectItem value="sandwich">Sandwich</SelectItem>
                  <SelectItem value="salad">Salad</SelectItem>
                  <SelectItem value="main">Main Course</SelectItem>
                  <SelectItem value="dessert">Dessert</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <!-- Summary -->
          <div class="bg-muted rounded-lg p-4">
            <div class="flex items-center justify-between">
              <span>{{ filteredRestaurants.length }} restaurants found</span>
              <span>{{ totalMealsAvailable }} meals available</span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>

    <!-- Results -->
    <div class="space-y-4">
      <Card v-if="filteredRestaurants.length === 0">
        <CardContent class="text-center py-8">
          <p class="text-muted-foreground">
            No restaurants or meals found matching your search criteria.
          </p>
        </CardContent>
      </Card>

      <Card 
        v-for="restaurant in filteredRestaurants" 
        :key="restaurant.id"
        :class="{ 'opacity-60': !restaurant.isOpen }"
      >
        <CardHeader>
          <div class="flex items-start justify-between">
            <div>
              <CardTitle class="flex items-center gap-2">
                {{ restaurant.name }}
                <Badge v-if="!restaurant.isOpen" variant="destructive">Closed</Badge>
              </CardTitle>
              <CardDescription class="flex items-center gap-4 mt-2">
                <span class="flex items-center gap-1">
                  <MapPin class="w-4 h-4" />
                  {{ restaurant.address }} • {{ restaurant.distance }}
                </span>
                <span class="flex items-center gap-1">
                  <Phone class="w-4 h-4" />
                  {{ restaurant.phone }}
                </span>
              </CardDescription>
            </div>
            <div class="text-right">
              <div class="flex items-center gap-1 mb-1">
                <Star class="w-4 h-4 fill-yellow-400 text-yellow-400" />
                <span>{{ restaurant.rating }}</span>
              </div>
              <Badge variant="secondary">{{ restaurant.cuisine }}</Badge>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <p v-if="restaurant.meals.length === 0" class="text-muted-foreground">
            No meals currently available
          </p>
          <template v-else>
            <div class="flex items-center gap-2 mb-4">
              <Utensils class="w-4 h-4" />
              <span>{{ restaurant.meals.length }} meal types • {{ getTotalServings(restaurant.meals) }} servings available</span>
            </div>
            <div class="space-y-3">
              <div 
                v-for="meal in restaurant.meals" 
                :key="meal.id"
                class="flex items-center justify-between p-3 bg-muted rounded-lg"
              >
                <div class="flex-1">
                  <div class="flex items-center gap-2 mb-1">
                    <h4>{{ meal.name }}</h4>
                    <Badge :class="getCategoryColor(meal.category)">
                      {{ meal.category }}
                    </Badge>
                  </div>
                  <p v-if="meal.description" class="text-muted-foreground text-sm mb-2">
                    {{ meal.description }}
                  </p>
                  <div class="flex items-center gap-4 text-sm text-muted-foreground">
                    <span>{{ meal.quantity }} servings</span>
                    <span class="flex items-center gap-1">
                      <Clock class="w-3 h-3" />
                      Until {{ meal.availableUntil }}
                    </span>
                  </div>
                </div>
                <Button 
                  :disabled="!restaurant.isOpen"
                  class="ml-4"
                >
                  Reserve
                </Button>
              </div>
            </div>
          </template>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { Badge } from './ui/badge'
import { Search, MapPin, Clock, Phone, Utensils, Star } from 'lucide-vue-next'

interface Meal {
  id: string
  name: string
  description: string
  category: string
  quantity: number
  availableUntil: string
}

interface Restaurant {
  id: string
  name: string
  address: string
  phone: string
  cuisine: string
  distance: string
  rating: number
  isOpen: boolean
  meals: Meal[]
}

const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Sunny Cafe",
    address: "123 Main St, Downtown",
    phone: "(555) 123-4567",
    cuisine: "American",
    distance: "0.5 mi",
    rating: 4.5,
    isOpen: true,
    meals: [
      {
        id: "1",
        name: "Vegetable Soup",
        description: "Fresh vegetable soup with bread",
        category: "soup",
        quantity: 20,
        availableUntil: "18:00"
      },
      {
        id: "2",
        name: "Chicken Sandwich",
        description: "Grilled chicken sandwich with salad",
        category: "sandwich",
        quantity: 15,
        availableUntil: "16:00"
      }
    ]
  },
  {
    id: "2",
    name: "Mario's Kitchen",
    address: "456 Oak Ave, Little Italy",
    phone: "(555) 234-5678",
    cuisine: "Italian",
    distance: "1.2 mi",
    rating: 4.8,
    isOpen: true,
    meals: [
      {
        id: "3",
        name: "Pasta Marinara",
        description: "Classic pasta with marinara sauce",
        category: "main",
        quantity: 12,
        availableUntil: "19:00"
      },
      {
        id: "4",
        name: "Caesar Salad",
        description: "Fresh romaine with parmesan and croutons",
        category: "salad",
        quantity: 8,
        availableUntil: "17:30"
      }
    ]
  },
  {
    id: "3",
    name: "Taco Express",
    address: "789 Pine St, Mexican Quarter",
    phone: "(555) 345-6789",
    cuisine: "Mexican",
    distance: "2.1 mi",
    rating: 4.3,
    isOpen: false,
    meals: []
  }
]

const searchQuery = ref("")
const selectedCuisine = ref("all")
const selectedCategory = ref("all")
const restaurants = ref<Restaurant[]>(mockRestaurants)

const filteredRestaurants = computed(() => {
  return restaurants.value.filter((restaurant) => {
    const matchesSearch = searchQuery.value === "" || 
      restaurant.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      restaurant.address.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      restaurant.meals.some(meal => 
        meal.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
        meal.description.toLowerCase().includes(searchQuery.value.toLowerCase())
      )
    
    const matchesCuisine = selectedCuisine.value === "all" || restaurant.cuisine === selectedCuisine.value
    
    const matchesCategory = selectedCategory.value === "all" || 
      restaurant.meals.some(meal => meal.category === selectedCategory.value)

    return matchesSearch && matchesCuisine && matchesCategory
  })
})

const totalMealsAvailable = computed(() => {
  return filteredRestaurants.value.reduce(
    (total, restaurant) => total + restaurant.meals.reduce((sum, meal) => sum + meal.quantity, 0),
    0
  )
})

const getCategoryColor = (category: string) => {
  const colors: { [key: string]: string } = {
    soup: "bg-blue-100 text-blue-800",
    sandwich: "bg-green-100 text-green-800",
    salad: "bg-yellow-100 text-yellow-800",
    main: "bg-red-100 text-red-800",
    dessert: "bg-purple-100 text-purple-800",
    other: "bg-gray-100 text-gray-800"
  }
  return colors[category] || colors.other
}

const getTotalServings = (meals: Meal[]) => {
  return meals.reduce((sum, meal) => sum + meal.quantity, 0)
}
</script>
