// BuchoCheioVuejs/src/components/RestaurantDashboard.vue
<template>
  <div class="mt-6 space-y-6">
    <!-- Add New Meal -->
    <Card>
      <CardHeader>
        <CardTitle class="flex items-center gap-2">
          <Plus class="w-5 h-5" />
          Add New Meal
        </CardTitle>
        <CardDescription>
          Add meals that are currently available for pickup.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form @submit.prevent="addMeal" class="space-y-4">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="mealName">Meal Name *</Label>
              <Input
                id="mealName"
                v-model="newMeal.name"
                placeholder="e.g., Vegetable Soup"
                required
              />
            </div>
            
            <div class="space-y-2">
              <Label for="category">Category</Label>
              <Select v-model="newMeal.category">
                <SelectTrigger>
                  <SelectValue placeholder="Select category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="soup">Soup</SelectItem>
                  <SelectItem value="sandwich">Sandwich</SelectItem>
                  <SelectItem value="salad">Salad</SelectItem>
                  <SelectItem value="main">Main Course</SelectItem>
                  <SelectItem value="dessert">Dessert</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div class="space-y-2">
            <Label for="description">Description</Label>
            <Textarea
              id="description"
              v-model="newMeal.description"
              placeholder="Brief description of the meal"
              :rows="2"
            />
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="quantity">Quantity Available *</Label>
              <Input
                id="quantity"
                type="number"
                min="1"
                v-model="newMeal.quantity"
                placeholder="How many servings?"
                required
              />
            </div>
            
            <div class="space-y-2">
              <Label for="availableUntil">Available Until *</Label>
              <Input
                id="availableUntil"
                type="time"
                v-model="newMeal.availableUntil"
                required
              />
            </div>
          </div>

          <Button type="submit" class="w-full">
            <Plus class="w-4 h-4 mr-2" />
            Add Meal
          </Button>
        </form>
      </CardContent>
    </Card>

    <!-- Current Meals -->
    <Card>
      <CardHeader>
        <CardTitle class="flex items-center gap-2">
          <Utensils class="w-5 h-5" />
          Current Available Meals
        </CardTitle>
        <CardDescription>
          Manage your currently available meals.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <p v-if="meals.length === 0" class="text-center text-muted-foreground py-8">
          No meals available. Add some meals above.
        </p>
        <div v-else class="space-y-4">
          <div 
            v-for="meal in meals" 
            :key="meal.id"
            class="flex items-center justify-between p-4 border rounded-lg"
          >
            <div class="flex-1">
              <div class="flex items-center gap-2 mb-2">
                <h4>{{ meal.name }}</h4>
                <Badge :class="getCategoryColor(meal.category)">
                  {{ meal.category }}
                </Badge>
              </div>
              <p v-if="meal.description" class="text-muted-foreground mb-2">
                {{ meal.description }}
              </p>
              <div class="flex items-center gap-4 text-sm text-muted-foreground">
                <span>{{ meal.quantity }} servings</span>
                <span>Until {{ meal.availableUntil }}</span>
              </div>
            </div>
            <Button
              variant="destructive"
              size="sm"
              @click="removeMeal(meal.id)"
            >
              <Trash2 class="w-4 h-4" />
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>

    <!-- Working Hours -->
    <Card>
      <CardHeader>
        <CardTitle class="flex items-center gap-2">
          <Clock class="w-5 h-5" />
          Update Working Hours
        </CardTitle>
        <CardDescription>
          Set your restaurant's operating hours for each day.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div class="space-y-4">
          <div 
            v-for="[day, hours] in Object.entries(workingHours)" 
            :key="day"
            class="flex items-center gap-4"
          >
            <div class="w-24 capitalize">{{ day }}</div>
            <div class="flex items-center gap-2 flex-1">
              <Input
                type="time"
                :model-value="hours.open"
                @input="updateHours(day, 'open', ($event.target as HTMLInputElement).value)"
                :disabled="!hours.isOpen"
                class="w-32"
              />
              <span>to</span>
              <Input
                type="time"
                :model-value="hours.close"
                @input="updateHours(day, 'close', ($event.target as HTMLInputElement).value)"
                :disabled="!hours.isOpen"
                class="w-32"
              />
              <Button
                :variant="hours.isOpen ? 'destructive' : 'default'"
                size="sm"
                @click="toggleDay(day)"
              >
                {{ hours.isOpen ? "Close" : "Open" }}
              </Button>
            </div>
          </div>
        </div>
        <Separator class="my-4" />
        <Button @click="updateWorkingHours" class="w-full">
          Update Working Hours
        </Button>
      </CardContent>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import { Textarea } from './ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { Badge } from './ui/badge'
import { Separator } from './ui/separator'
import { toast } from 'sonner@2.0.3'
import { Plus, Clock, Utensils, Trash2 } from 'lucide-vue-next'

interface Meal {
  id: string
  name: string
  description: string
  category: string
  quantity: number
  availableUntil: string
}

interface WorkingDay {
  open: string
  close: string
  isOpen: boolean
}

const meals = ref<Meal[]>([
  {
    id: "1",
    name: "Vegetable Soup",
    description: "Fresh vegetable soup with bread",
    category: "soup",
    quantity: 20,
    availableUntil: "18:00"
  },
  {
    id: "2",
    name: "Chicken Sandwich",
    description: "Grilled chicken sandwich with salad",
    category: "sandwich",
    quantity: 15,
    availableUntil: "16:00"
  }
])

const newMeal = ref({
  name: "",
  description: "",
  category: "",
  quantity: "",
  availableUntil: ""
})

const workingHours = ref<Record<string, WorkingDay>>({
  monday: { open: "09:00", close: "18:00", isOpen: true },
  tuesday: { open: "09:00", close: "18:00", isOpen: true },
  wednesday: { open: "09:00", close: "18:00", isOpen: true },
  thursday: { open: "09:00", close: "18:00", isOpen: true },
  friday: { open: "09:00", close: "18:00", isOpen: true },
  saturday: { open: "10:00", close: "16:00", isOpen: true },
  sunday: { open: "10:00", close: "16:00", isOpen: false }
})

const addMeal = () => {
  if (!newMeal.value.name || !newMeal.value.quantity || !newMeal.value.availableUntil) {
    toast.error("Please fill in all required fields")
    return
  }

  const meal: Meal = {
    id: Date.now().toString(),
    name: newMeal.value.name,
    description: newMeal.value.description,
    category: newMeal.value.category || "other",
    quantity: parseInt(newMeal.value.quantity),
    availableUntil: newMeal.value.availableUntil
  }

  meals.value.push(meal)
  newMeal.value = { name: "", description: "", category: "", quantity: "", availableUntil: "" }
  toast.success("Meal added successfully!")
}

const removeMeal = (id: string) => {
  meals.value = meals.value.filter(meal => meal.id !== id)
  toast.success("Meal removed")
}

const updateHours = (day: string, field: 'open' | 'close', value: string) => {
  workingHours.value[day][field] = value
}

const toggleDay = (day: string) => {
  workingHours.value[day].isOpen = !workingHours.value[day].isOpen
}

const updateWorkingHours = () => {
  toast.success("Working hours updated successfully!")
}

const getCategoryColor = (category: string) => {
  const colors: { [key: string]: string } = {
    soup: "bg-blue-100 text-blue-800",
    sandwich: "bg-green-100 text-green-800",
    salad: "bg-yellow-100 text-yellow-800",
    main: "bg-red-100 text-red-800",
    dessert: "bg-purple-100 text-purple-800",
    other: "bg-gray-100 text-gray-800"
  }
  return colors[category] || colors.other
}
</script>

// BuchoCheioVuejs/src/components/RestaurantDashboard.tsx
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Textarea } from "./ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Badge } from "./ui/badge";
import { Separator } from "./ui/separator";
import { toast } from "sonner@2.0.3";
import { Plus, Clock, Utensils, Trash2, Edit } from "lucide-react";

interface Meal {
  id: string;
  name: string;
  description: string;
  category: string;
  quantity: number;
  availableUntil: string;
}

export function RestaurantDashboard() {
  const [meals, setMeals] = useState<Meal[]>([
    {
      id: "1",
      name: "Sopa de Legumes",
      description: "Sopa fresca de legumes com pão",
      category: "sopa",
      quantity: 20,
      availableUntil: "18:00"
    },
    {
      id: "2",
      name: "Sanduíche de Frango",
      description: "Sanduíche de frango grelhado com salada",
      category: "sanduiche",
      quantity: 15,
      availableUntil: "16:00"
    }
  ]);

  const [newMeal, setNewMeal] = useState({
    name: "",
    description: "",
    category: "",
    quantity: "",
    availableUntil: ""
  });

  const [workingHours, setWorkingHours] = useState({
    segunda: { open: "09:00", close: "18:00", isOpen: true },
    terca: { open: "09:00", close: "18:00", isOpen: true },
    quarta: { open: "09:00", close: "18:00", isOpen: true },
    quinta: { open: "09:00", close: "18:00", isOpen: true },
    sexta: { open: "09:00", close: "18:00", isOpen: true },
    sabado: { open: "10:00", close: "16:00", isOpen: true },
    domingo: { open: "10:00", close: "16:00", isOpen: false }
  });

  const addMeal = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMeal.name || !newMeal.quantity || !newMeal.availableUntil) {
      toast.error("Por favor, preencha todos os campos obrigatórios");
      return;
    }

    const meal: Meal = {
      id: Date.now().toString(),
      name: newMeal.name,
      description: newMeal.description,
      category: newMeal.category || "outro",
      quantity: parseInt(newMeal.quantity),
      availableUntil: newMeal.availableUntil
    };

    setMeals(prev => [...prev, meal]);
    setNewMeal({ name: "", description: "", category: "", quantity: "", availableUntil: "" });
    toast.success("Refeição adicionada com sucesso!");
  };

  const removeMeal = (id: string) => {
    setMeals(prev => prev.filter(meal => meal.id !== id));
    toast.success("Refeição removida");
  };

  const updateWorkingHours = () => {
    toast.success("Horários de funcionamento atualizados com sucesso!");
  };

  const getCategoryColor = (category: string) => {
    const colors: { [key: string]: string } = {
      sopa: "bg-blue-100 text-blue-800",
      sanduiche: "bg-green-100 text-green-800",
      salada: "bg-yellow-100 text-yellow-800",
      principal: "bg-red-100 text-red-800",
      sobremesa: "bg-purple-100 text-purple-800",
      outro: "bg-gray-100 text-gray-800"
    };
    return colors[category] || colors.outro;
  };

  return (
    <div className="mt-6 space-y-6">
      {/* Add New Meal */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Plus className="w-5 h-5" />
            Adicionar Nova Refeição
          </CardTitle>
          <CardDescription>
            Adicione refeições que estão disponíveis para retirada.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={addMeal} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="mealName">Nome da Refeição *</Label>
                <Input
                  id="mealName"
                  value={newMeal.name}
                  onChange={(e) => setNewMeal(prev => ({ ...prev, name: e.target.value }))}
                  placeholder="ex: Sopa de Legumes"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="category">Categoria</Label>
                <Select value={newMeal.category} onValueChange={(value) => setNewMeal(prev => ({ ...prev, category: value }))}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecionar categoria" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sopa">Sopa</SelectItem>
                    <SelectItem value="sanduiche">Sanduíche</SelectItem>
                    <SelectItem value="salada">Salada</SelectItem>
                    <SelectItem value="principal">Prato Principal</SelectItem>
                    <SelectItem value="sobremesa">Sobremesa</SelectItem>
                    <SelectItem value="outro">Outro</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Descrição</Label>
              <Textarea
                id="description"
                value={newMeal.description}
                onChange={(e) => setNewMeal(prev => ({ ...prev, description: e.target.value }))}
                placeholder="Breve descrição da refeição"
                rows={2}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="quantity">Quantidade Disponível *</Label>
                <Input
                  id="quantity"
                  type="number"
                  min="1"
                  value={newMeal.quantity}
                  onChange={(e) => setNewMeal(prev => ({ ...prev, quantity: e.target.value }))}
                  placeholder="Quantas porções?"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="availableUntil">Disponível Até *</Label>
                <Input
                  id="availableUntil"
                  type="time"
                  value={newMeal.availableUntil}
                  onChange={(e) => setNewMeal(prev => ({ ...prev, availableUntil: e.target.value }))}
                  required
                />
              </div>
            </div>

            <Button type="submit" className="w-full">
              <Plus className="w-4 h-4 mr-2" />
              Adicionar Refeição
            </Button>
          </form>
        </CardContent>
      </Card>

      {/* Current Meals */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Utensils className="w-5 h-5" />
            Refeições Disponíveis Atualmente
          </CardTitle>
          <CardDescription>
            Gerencie suas refeições disponíveis no momento.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {meals.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              Nenhuma refeição disponível. Adicione algumas refeições acima.
            </p>
          ) : (
            <div className="space-y-4">
              {meals.map((meal) => (
                <div key={meal.id} className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <h4>{meal.name}</h4>
                      <Badge className={getCategoryColor(meal.category)}>
                        {meal.category}
                      </Badge>
                    </div>
                    {meal.description && (
                      <p className="text-muted-foreground mb-2">{meal.description}</p>
                    )}
                    <div className="flex items-center gap-4 text-sm text-muted-foreground">
                      <span>{meal.quantity} porções</span>
                      <span>Até {meal.availableUntil}</span>
                    </div>
                  </div>
                  <Button
                    variant="destructive"
                    size="sm"
                    onClick={() => removeMeal(meal.id)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Working Hours */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="w-5 h-5" />
            Atualizar Horários de Funcionamento
          </CardTitle>
          <CardDescription>
            Defina os horários de funcionamento do seu restaurante para cada dia.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {Object.entries(workingHours).map(([day, hours]) => (
              <div key={day} className="flex items-center gap-4">
                <div className="w-24 capitalize">{day}</div>
                <div className="flex items-center gap-2 flex-1">
                  <Input
                    type="time"
                    value={hours.open}
                    onChange={(e) => setWorkingHours(prev => ({
                      ...prev,
                      [day]: { ...prev[day as keyof typeof prev], open: e.target.value }
                    }))}
                    disabled={!hours.isOpen}
                    className="w-32"
                  />
                  <span>às</span>
                  <Input
                    type="time"
                    value={hours.close}
                    onChange={(e) => setWorkingHours(prev => ({
                      ...prev,
                      [day]: { ...prev[day as keyof typeof prev], close: e.target.value }
                    }))}
                    disabled={!hours.isOpen}
                    className="w-32"
                  />
                  <Button
                    variant={hours.isOpen ? "destructive" : "default"}
                    size="sm"
                    onClick={() => setWorkingHours(prev => ({
                      ...prev,
                      [day]: { ...prev[day as keyof typeof prev], isOpen: !hours.isOpen }
                    }))}
                  >
                    {hours.isOpen ? "Close" : "Open"}
                  </Button>
                </div>
              </div>
            ))}
          </div>
          <Separator className="my-4" />
          <Button onClick={updateWorkingHours} className="w-full">
            Update Working Hours
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
